### PR TITLE
Error when there are no location items.

### PR DESCRIPTION
**Pull request by gsterndale**
default_point option added

### CODE REVIEW

**Comment by cinematreasures** [comment]
+1 for this patch.

I'm trying to map a list of addresses in a given region. This provides a nice fallback when a given region does not contain any mappable addresses. That way, you can still map the containing region itself (instead of having an empty map).

**Comment by mokolabs** [comment]
FYI... the above comment was posted by me. (I was logged into the wrong account.)

**Comment by brianjlandau** [comment]
Thanks!

**Comment by gsterndale** [comment]
Thank **you**

**Pull request merged**
